### ISSUE TITLE
ISY-994i

### ISSUE THREAD

**Issue by ookami85** [rllynch/smartthings-isy994i#1]
Thank you very much for this integration. Is it possible to have brightness control within SmartThings? Also are there any plans to make this compatible with scenes or programs?

Best regards,

Gene

**Comment by rllynch** [comment]
Scene/programs might be a little challenging, but let me see about adding a dimmer devicetype.

**Comment by ookami85** [comment]
Fantastic, this is really assisting in tying all my devices together.  Also, are Fanlincs and secondary Keypadlinc buttons not supported? I tried adding a Fanlinc and the light portion works but the fan only partly works. When pushing the ON button in the SmartThings app nothing happens, although if the fan is on, pushing the OFF button within the app will turn the fan off. In relation to Keypadlincs, the primary button (A) works but the other buttons (B-H) show in the SmartThings app but don't seem to respond. All assistance is appreciated. I am just trying to learn what is and isn't possible.

 Best regards,

Gene

**Comment by rllynch** [comment]
I don't have a Fanlinc so it's not supported, although it sounds like it's probably a minor tweak to the "on" code (perhaps try the new dimmer devicetype?).  Keypadlincs should work - if you turn it on/off from SmartThings it should turn on/off the light/appliance connected to the Keypadlinc.  However, triggering scenes associated with the Keypadlinc buttons is not supported.

I've added a devicetype that can control dimmers via the ISY994i.  You can try it out by updating your existing SmartThings ISY app and device type with app.groovy and devicetype-switch.groovy, then creating a new devicetype for devicetype-dimmer.groovy.  Finally, go to https://graph.api.smartthings.com/device/list and change the Type of each dimmer to ISY Dimmer (the new devicetype).  You should then be able to dim them and query their brightless level from SmartThings.

**Comment by ookami85** [comment]
Thank you! Dimming is working great. In fact, if it helps, the Fanlincs are somewhat working too. Once  under the dimmer device type, when the dimmer is set to around 33% the Fanlinc is set to low, 66% medium, and 100% high. Now to see if I can work around this with SmartTitles & Routines. I appreciate all that you've done on this. Let me know if I can be of any assistance or if you post any updates.  

Gene
