### ISSUE TITLE
getdatavalue error

### ISSUE THREAD

**Issue by jjslegacy** [rllynch/smartthings-isy994i#4]
Not sure if you are still do much with this but last few days I have started getting an odd error and I am not sure why.  During a refresh in the logs I see:

 java.lang.IllegalArgumentException: Command 'getDataValue' is not supported by device f2492ec6-017f-405d-93cd-bef5965940e0 of type 'ISY Switch'. Supported commands: [on, off, poll, refresh] @ line 66

Any ideas?

**Comment by rllynch** [comment]
I'm seeing it too.  I think SmartThings changed their API a little bit and restricted one device from being able to perform getDataValue on another device.  I'm trying to find an alternate approach.

**Comment by jjslegacy** [comment]
Thank you - much appreciated - your code has been excellent and I truly appreciate it!

**Comment by jjslegacy** [comment]
Not sure if this helps but got a suggestion here or you can comment to get some more info. https://community.smartthings.com/t/command-getdatavalue-is-not-supported-by-device/57192/4

**Comment by rllynch** [comment]
I found that switching from getChildDevices() to getAllChildDevices() fixes the problem.  Oddly, explicitly specifying the default value for the first argument also fixes the problem (i.e. getChildDevices(false) instead of just getChildDevices()). I've committed the fix.  Let me know if it works for you.

**Comment by jjslegacy** [comment]
That works for me - great find.  Totally weird though. Again thanks for this code - works great for me.

**Comment by jjslegacy** [comment]
I have at least one device that I can't get it to refresh its status and not sure why.  I also see this randomly in the logs:   java.lang.NumberFormatException: empty String @ line 88

**Comment by jjslegacy** [comment]
I think I have fixed it.  I have a few devices that aren't plugged in all the time (outdoor outlets).

I am guessing the unplugged ones don't give a response your code is expecting.  To cover all bases (I didnt feel like debugging to see which it was :) )  I added:

  if (child.getDataValue("nodeAddr") == nodeAddr) {
                    def value = 'on'
                    if (status == '0') {
                        value = 'off'
                    }
                    _**added                    if (status == null || status == '' || status ==' ')
*__added                    {
*__added                    status='0'
*__added                    value='off'
*_*added                    }

Probably a one off case for me but seems to be good to go now.  I had this problem earlier and had this added to only the switch but somehow now need it added to dimmer code also

**Comment by rllynch** [comment]
Thanks for the fix.  I can't seem to reproduce that problem locally, but I've put in a try/catch for the NumberFormatException that should gracefully handle this case and will also log some clues about what's going on.

**Comment by jjslegacy** [comment]
That does look prettier :)   It only seems to be for devices that aren't attached to the system - I have some outdoor plugin outlets that I only use sometimes.
Now I see this:
Exception parsing : java.lang.NumberFormatException: empty String (will assume device is off)
Here is the rest status example:
`<node id="31 A1 61 1"><property id="ST" value=" " formatted=" " uom="on/off"/></node>`
