### ISSUE TITLE
Device Types

### ISSUE THREAD

**Issue by macjeff** [rllynch/smartthings-isy994i#6]
I notice there is another plugin for isy and Smartthings

https://github.com/rodtoll/smartthings-isy

so do they work together?  The other has more device types.

Sorry if this is a stupid question but want to know which way to go with this

**Comment by rllynch** [comment]
They were developed separately so they don't work together.  I phased out my Insteon stuff a few months ago, and it looks like the other one was developed farther, so you're probably better off with rodtoll's plugin.

**Comment by macjeff** [comment]
I cant get his working.  The smart App works but I cant get the devices to show up even though they are in as device handlers.    Yours works but I am looking to get some z-wave locks over and only the other plugin has that device handler.  Any way to get it to work with yours?

**Comment by rllynch** [comment]
Unfortunately, they're too different so there isn't an easy way to make them work together.
